exports.languages = [
  "🇺🇸 English",
  "🇪🇸 Spanish",
  "🇫🇷 French",
  "🇩🇪 German",
  "🇸🇦 Arabic",
  "🇨🇳 Chinese",
  "🇩🇰 Danish",
  "🇳🇱 Dutch",
  "🇬🇷 Greek",
  "🇮🇱 Hebrew",
  "🇮🇳 Hindi",
  "🇭🇺 Hungarian",
  "🇮🇸 Icelandic",
  "🇮🇩 Indonesian",
  "🇮🇹 Italian",
  "🇯🇵 Japanese",
  "🇰🇷 Korean",
  "🇲🇾 Malay",
  "🇳🇴 Norwegian",
  "🇵🇱 Polish",
  "🇵🇹 Portuguese",
  "🇷🇴 Romanian",
  "🇷🇺 Russian",
  "🇸🇪 Swedish",
  "🇹🇷 Turkish",
  "🏴 Welsh",
];

exports.languageCode = {
  Arabic: "arb",
  Chinese: "cmn-CN",
  Danish: "da-DK",
  Dutch: "nl-NL",
  English: "en-US",
  French: "fr-FR",
  German: "de-DE",
  Greek: "el-GR",
  Hebrew: "he-IL",
  Hindi: "hi-IN",
  Hungarian: "hu-HU",
  Icelandic: "is-IS",
  Indonesian: "id-ID",
  Italian: "it-IT",
  Japanese: "ja-JP",
  Korean: "ko-KR",
  Malay: "ms-MY",
  Norwegian: "nb-NO",
  Polish: "pl-PL",
  Portuguese: "pt-PT",
  Romanian: "ro-RO",
  Russian: "ru-RU",
  Spanish: "es-ES",
  Swedish: "sv-SE",
  Turkish: "tr-TR",
  Welsh: "cy-GB",
};
